version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Files
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - mynetwork

  web:
    build: .
    command: sh init.sh
    volumes:
      - .:/filemanager
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    deploy:
      replicas: 3 
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  mynetwork:
