# Generated by Django 4.2.7 on 2023-11-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_optionmenu_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': True},
        ),
    ]
