# Generated by Django 4.2.7 on 2023-11-09 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_alter_file_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
