# Generated by Django 4.2.7 on 2023-11-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0011_remove_file_ubication_file_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='img',
        ),
        migrations.AddField(
            model_name='file',
            name='ubication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
