# Generated by Django 4.2.7 on 2023-11-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0012_remove_file_img_file_ubication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ubication',
        ),
        migrations.AddField(
            model_name='file',
            name='img',
            field=models.ImageField(default=None, upload_to='imgs'),
            preserve_default=False,
        ),
    ]
